### ISSUE TITLE
add setup script

### ISSUE THREAD

**Issue by adendek** [adendek/utorch#4]
Add setup script. It can be done by following [this](https://stackoverflow.com/a/39811884/1877600) tutorial.

**Comment by i-noza** [comment]
hello, i am new to open source and github, but i think i can help with this issue, so if no one is working on it, assign it to me

**Comment by adendek** [comment]
Hello, @i-noza 
Sure, please send PR. I'll review it and if it works I'll merge it. 
I hope that you are aware that this is not PyTorch by Facebook. It is my personal project which aims is to implement an understandable and minimal version of PyTorch.   
PS. 
Just out of curiosity, how did you find this project?

**Comment by i-noza** [comment]
I just searched for issues with label "good first issue" and came across your project.

**Comment by adendek** [comment]
This issue is now resolved. I strongly encourage you to take a look at the remaining ones.
